version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: colegio-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - colegio-net

  eureka-server:
    build: ./plataformaescolar
    ports:
      - "8761:8761"
    networks:
      - colegio-net
    command: mvn spring-boot:run -pl infraestructuredomain/eurekaServer

  estudiante-service:
    build: ./plataformaescolar
    ports:
      - "9091:9091"
    networks:
      - colegio-net
    command: mvn spring-boot:run -pl schooldomain/estudiante

  asistencia-service:
    build: ./plataformaescolar
    ports:
      - "9093:9093"
    networks:
      - colegio-net
    command: mvn spring-boot:run -pl schooldomain/asistencia

  evaluacion-service:
    build: ./plataformaescolar
    ports:
      - "9092:9092"
    networks:
      - colegio-net
    command: mvn spring-boot:run -pl schooldomain/evaluacion

  apigateway:
    build: ./plataformaescolar
    ports:
      - "8080:8080"
    networks:
      - colegio-net
    command: mvn spring-boot:run -pl infraestructuredomain/apigateway

networks:
  colegio-net: