spring.application.name=keycloakadapter
server.port=8088

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

keycloak.authorization-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/auth
keycloak.user-info-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/userinfo
keycloak.token-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/token
keycloak.logout=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/certs

keycloak.client-id=front-client-app
keycloak.client-secret=ZqGVuItI8d4fPQUFXPWAwzNnaY7Fs4on
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.root=INFO
keycloak.certs-id=8R1q9LwVjC9S5XMchvf6AFlL_ICdDtj3N9IQxMF3G1Y