spring.application.name=keycloakadapter
server.port=8088

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

keycloak.authorization-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/auth
keycloak.user-info-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/userinfo
keycloak.token-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/token
keycloak.logout=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://keycloak-server:8080/realms/Colegio/protocol/openid-connect/certs

keycloak.client-id=front-client-app
keycloak.client-secret=WeAfnEf3w0xY9U2adFFsFzytnZYLp4OA
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

logging.level.root=INFO
keycloak.certs-id=y4PTco7anVbEBrkWxCKPyKy1lkiv3LM3d0oRiQbiH2Q