spring.application.name=bff-service
server.port=9000

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

services.estudiante.url=http://estudiante-service:9091/estudiante
services.asistencia.url=http://asistencia-service:9093/asistencia
services.calificacion.url=http://evaluacion-service:9092/calificacion