spring.application.name=apigateway
server.port=8080

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

spring.cloud.gateway.routes[0].id=estudiante-route
spring.cloud.gateway.routes[0].uri=lb://estudiante-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/estudiante/**

spring.cloud.gateway.routes[1].id=asistencia-route
spring.cloud.gateway.routes[1].uri=lb://asistencia-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/asistencia/**

spring.cloud.gateway.routes[2].id=evaluacion-route
spring.cloud.gateway.routes[2].uri=lb://evaluacion-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/evaluacion/**